import os
from datetime import datetime
from pathlib import Path
from typing import Optional

from github import Auth, Github, GithubException
from github.InputGitTreeElement import InputGitTreeElement


class GitHubPublisher:
    """
    Публикует сгенерированные Rust-файлы в GitHub-репозиторий:
    - создаёт новую ветку
    - формирует один commit со всеми файлами (через Git Tree API)
    - создаёт Pull Request
    """

    def __init__(
        self,
        repo_name: str,
        token: Optional[str] = None,
        base_branch: str = "main",
        reviewer: Optional[str] = None,
    ):
        self.token = token or os.getenv("GITHUB_TOKEN")
        if not self.token:
            raise ValueError(
                "GITHUB_TOKEN не задан. Укажите его в переменных окружения."
            )

        self.gh = Github(auth=Auth.Token(self.token))
        self.repo = self.gh.get_repo(repo_name)
        self.base_branch = base_branch
        self.reviewer = reviewer

    def publish(
        self,
        generated_dir: Path,
        target_path: str = "src/incus/generated_prototype",
        branch_prefix: str = "sync/auto",
    ) -> str:
        """
        Публикует содержимое generated_dir в GitHub-репозиторий.
        Возвращает URL созданного Pull Request.
        """
        if not generated_dir.exists():
            raise ValueError(f"Каталог не найден: {generated_dir}")

        files = sorted(generated_dir.glob("*.rs"))
        if not files:
            raise ValueError(f"В каталоге {generated_dir} не найдено .rs файлов")

        timestamp = datetime.now().strftime("%Y-%m-%d-%H%M%S")
        branch_name = f"{branch_prefix}-{timestamp}"

        print(f"📦 Подготовка публикации {len(files)} файлов...")
        print(f"📁 Источник: {generated_dir}")
        print(f"📂 Целевой путь в репозитории: {target_path}")

        # 1. Получаем последний commit базовой ветки
        base_branch_obj = self.repo.get_branch(self.base_branch)
        base_commit = self.repo.get_git_commit(base_branch_obj.commit.sha)
        base_tree = base_commit.tree

        # 2. Формируем новое дерево поверх base_tree
        elements = []
        for file_path in files:
            content = file_path.read_text(encoding="utf-8")
            repo_file_path = f"{target_path}/{file_path.name}"

            elements.append(
                InputGitTreeElement(
                    path=repo_file_path,
                    mode="100644",
                    type="blob",
                    content=content,
                )
            )

        new_tree = self.repo.create_git_tree(elements, base_tree)

        # 3. Создаём один общий commit
        commit_message = (
            f"🤖 Auto-sync Incus models ({timestamp})\n\n"
            f"Generated by incus-model-sync."
        )
        new_commit = self.repo.create_git_commit(
            commit_message,
            new_tree,
            [base_commit],
        )

        # 4. Создаём новую ветку от этого commit
        self.repo.create_git_ref(
            ref=f"refs/heads/{branch_name}",
            sha=new_commit.sha,
        )
        print(f"🌿 Ветка создана: {branch_name}")

        # 5. Открываем Pull Request
        pr_title = f"🔄 Auto-sync Incus models ({timestamp})"
        pr_body = self._build_pr_body(files)

        pr = self.repo.create_pull(
            title=pr_title,
            body=pr_body,
            head=branch_name,
            base=self.base_branch,
        )

        print(f"📬 Pull Request создан: {pr.html_url}")

        # 6. Назначаем ревьюера (если задан)
        if self.reviewer:
            try:
                pr.create_review_request(reviewers=[self.reviewer])
                print(f"👤 Назначен ревьюер: {self.reviewer}")
            except GithubException as e:
                print(f"⚠️ Не удалось назначить ревьюера: {e}")

        return pr.html_url

    def _build_pr_body(self, files: list[Path]) -> str:
        file_list = "\n".join(f"- `{f.name}`" for f in files)

        return f"""## 🤖 Автоматическая синхронизация моделей Incus

Этот Pull Request создан автоматически системой `incus-model-sync`.

### Что изменилось
Обновлены Rust DTO-модели на основе изменений в Go-репозитории Incus.

### Затронутые файлы ({len(files)} шт.)
{file_list}

### Статус
- ✅ Генерация выполнена успешно
- ✅ Финальная компиляционная валидация (`cargo check`) пройдена
- ✅ DTO подготовлены к review и merge

### Действия для инженера
Пожалуйста, проверьте изменения и выполните merge, если всё корректно.
"""